config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  root 'static_pages#home'

  resources :vendors, only: [ :create ]
  resources :trades
  resources :boards

  get 'trade-signup',       to: "vendors#new"
  get 'vendor-signup',      to: "trades#new"
  get 'vendor-onboarding',  to: "boards#new"

  get 'trade_success',         to: 'static_pages#trade'
  get 'vendor_success',        to: 'static_pages#vendor'
  get 'board_success',         to: 'static_pages#board'
  get 'board_success_update',  to: 'static_pages#board_update'
  get 'trade_success_update',  to: 'static_pages#trade_update'
  get 'about',                 to: 'static_pages#about'
  get 'product_categories',    to: 'static_pages#product_categories'
  get 'upload_vendor_agreement_success',  to: 'static_pages#upload_vendor_agreement_success'

  get 'persons/profile', as: 'user_root'
  get 'upload-vendor-agreement-new',  to: 'persons#upload_vendor_agreement_new'
  post 'upload-vendor-agreement-new', to: 'persons#upload_vendor_agreement_create'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/board.rb
class Board < ActiveRecord::Base
  has_many :brands
  has_many :transportation_and_shipments
  has_many :vendor_carriers
  has_many :arbor_gentry_carriers
  has_many :product_types

  belongs_to :user, :dependent => :destroy

  mount_uploader :w_9_form, ImageUploader
  mount_uploader :certificate, ImageUploader


  accepts_nested_attributes_for :brands, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :transportation_and_shipments, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :vendor_carriers, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :arbor_gentry_carriers, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :product_types, reject_if: :all_blank, allow_destroy: true

  validates :primary_business_email, presence:  true

  def display_name
    # "#{first_name} #{last_name}"
  end
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  belongs_to :board
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :trade_categories, dependent: :destroy
  has_many :trades, through: :trade_categories
end

app/models/channel.rb
class Channel < ActiveRecord::Base
  has_many :trade_channels, dependent: :destroy
  has_many :trades, through: :trade_channels
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :vendor_companies, dependent: :destroy
  has_many :vendors, through: :vendor_companies
end

app/models/greeting.rb
class Greeting < ActiveRecord::Base
end

app/models/option.rb
class Option < ActiveRecord::Base
  has_many :trade_options, dependent: :destroy
  has_many :trades, through: :trade_options
end

app/models/product_type.rb
class ProductType < ActiveRecord::Base
  belongs_to :board
end

app/models/trade.rb
class Trade < ActiveRecord::Base

  belongs_to :user, :dependent => :destroy

  has_many :categories, :through =>  :trade_categories
  has_many :trade_categories, dependent: :destroy

  has_many :channels, :through =>  :trade_channels
  has_many :trade_channels, dependent: :destroy

  has_many :options, :through =>  :trade_options
  has_many :trade_options, dependent: :destroy

  has_many :information_trades, :dependent => :destroy

  validates :business_name, :greeting, :first_name, :last_name, :email, :phone_number, :address,
            :city, :state, :zipcode, :country, :web_site_url_my, presence:  true

  mount_uploader :image, ImageUploader

end

app/models/trade_category.rb
class TradeCategory < ActiveRecord::Base
  belongs_to :trade
  belongs_to :category
end

app/models/trade_channel.rb
class TradeChannel < ActiveRecord::Base
  belongs_to :trade
  belongs_to :channel
end

app/models/trade_option.rb
class TradeOption < ActiveRecord::Base
  belongs_to :trade
  belongs_to :option
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :board
  has_one :trade
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base

  has_many :companies, :through =>  :vendor_companies
  has_many :vendor_companies, dependent: :destroy

  validates :business_name, :greeting, :first_name, :last_name, :email, :phone_number, :address,
            :city, :state, :zipcode, :country, :web_site_url, presence:  true

  mount_uploader :image, ImageUploader

end

app/models/vendor_carrier.rb
class VendorCarrier < ActiveRecord::Base
  belongs_to :board
end

app/models/vendor_company.rb
class VendorCompany < ActiveRecord::Base
  belongs_to :vendor
  belongs_to :company
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trade Application – Tandem Arbor/Arbor Gentry</title>
  <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Playfair+Display"/>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <%= render 'shared/header' %>
  <% flash.each do |key, value| %>
      <% if key == "notice" %>
      <% elsif value == "Invalid Email or password." %>
          <div class="text-center <%= flash_class(key) %>">
            <p>Sorry, but the username/password combination you entered is incorrect. Please try again.</p>
          </div>
      <% else %>
          <div class="text-center <%= flash_class(key) %>">
            <p><%= value %></p>
          </div>
      <% end %>
  <% end %>
  <%= yield %>
  <%= render 'shared/footer' %>
</div>
</body>
</html>

app/views/shared/_footer.html.erb
<div class="row ta-Footer">
  <div class="col-md-2 col-sm-12">
    <%= image_tag("avant-logo.jpg", :alt => "img") %>
  </div>
  <div class="col-md-2 col-sm-12 ta-FooterListColumn">
    <h1>Let Us Help You</h1>
    <ul>
      <li><a href="tel:8003064504">800 306 4504</a></li>
      <li><a href="http://tandemarbor.com/community/contact">Contact Us</a></li>
      <li><a href="http://tandemarbor.com/pages/customer-service/#order-tracking">Order Tracking</a></li>
      <li><a href="http://tandemarbor.com/pages/customer-service/#shipping-delivery">Shipping & Delivery</a></li>
      <li><a href="http://tandemarbor.com/pages/customer-service/#returns-exchanges">Returns & Exchanges</a></li>
      <li><a href="http://tandemarbor.com/pages/factory-old">Factory</a></li>
      <li><a href="http://tandemarbor.com/pages/curate-old">Curate</a></li>
    </ul>
  </div>
  <div class="col-md-2 col-sm-12 ta-FooterListColumn">
    <h1>Our Company</h1>
    <ul>
      <li><a href="http://tandemarbor.com/pages/about-us">About Tandem Arbor</a></li>
      <li><a href="http://tandemarbor.com/pages/about-us/#financing">Financing</a></li>
      <li><a href="http://tandemarbor.com/pages/about-us/#careers">Careers</a></li>
      <li><a href="http://tandemarbor.com/pages/terms-of-use">Terms of Use</a></li>
      <li><a href="http://tandemarbor.com/pages/about-us/#investors">Investor Relations</a></li>
    </ul>
  </div>
  <div class="col-md-2 col-sm-12 ta-FooterListColumn">
    <h1>Resources</h1>
    <ul>
      <li><a href="http://tandemarbor.com/pages/measuring-guide">Measuring Guide</a></li>
      <li><a href="http://www.tandemarbor.com/vpd">Very Personal Decorator</a></li>
      <li><a href="http://tandemarbor.com/">Retail Licensing Program</a></li>
      <li><a href="https://vendors.arborgentry.com">Become A Vendor</a></li>
      <li><a href="https://vendors.arborgentry.com/trade-signup">Trade Program</a></li>
      <li><a href="http://design.tandemarbor.com/">Design Services</a></li>
    </ul>
  </div>
  <!--<div class="col-md-4 col-sm-12 ta-FooterListColumn">-->
    <!--<h1>Like Being First?</h1>-->
    <!--<div class="row">-->
      <!--<div class="col-md-12">-->
        <!--MAILCHIMP MAILER-->
      <!--</div>-->
    <!--</div>-->
    <!--<div class="row">-->
      <!--<div class="col-md-12">-->
        <!--Get To Know Us-->
      <!--</div>-->
    <!--</div>-->
  <!--</div>-->
</div>
<div class="row ta-SubFooter">
  <ul>
    <li><a href="">Terms of Use</a></li>
    <li><a href="">Privacy Policy</a></li>
    <li><a href="">Site Map</a></li>
    <li><a href="">&copy; 2016 Arbor Gentry, LLC</a></li>
  </ul>
</div>

app/views/shared/_header.html.erb
<div class="row ta-CustomerNav">
  <div class="col-md-6 col-sm-12 ta-CustomerNavLeft">
    <ul class="ta-CustomerMenu">
      <li><a href="http://tandemarbor.com/pages/customer-service">Customer Service</a></li>
      <li><a href="http://tandemarbor.com/pages/about-us">About</a></li>
      <li><a href="https://www.tandemarbor.com">Return to TandemArbor.com</a></li>
    </ul>
  </div>
  <div class="col-md-6 col-sm-12 ta-CustomerNavRight">
    <ul class="ta-CustomerMenu">
      <li><a href="http://tandemarbor.com/pages/customer-service">Avant Blog</a></li>
      <li><a href="http://tandemarbor.com/pages/very-personal-decorator">Very Personal Decorator</a></li>
      <li><a href="http://tandemarbor.com/pages/factory">Factory</a></li>
      <li><a href="http://tandemarbor.com/pages/curate">Curate</a></li>
    </ul>
  </div>
</div>
<div class="row">
  <div class="col-md-4 col-md-offset-4 ta-HeaderLogo">
    <% if user_signed_in? %>
        <%= link_to user_root_path do %>
            <img style="width: 277px; height: 88px;" id="logoImg" src="https://tandemarbor.azureedge.net/navigationimages/logo-stopped.png" data-status="still" alt=""/>
        <% end %>
    <% else %>
        <%= link_to root_path do %>
            <img style="width: 277px; height: 88px;" id="logoImg" src="https://tandemarbor.azureedge.net/navigationimages/logo-stopped.png" data-status="still" alt=""/>
        <% end %>
    <% end %>
  </div>
</div>
<div class="row ta-PrimaryNavigation">
  <div class="col-md-6 col-sm-12">
    <ul class="ta-PrimaryNavigationLinks" style="float: left;">
      <li><%= link_to "About", about_path %></li>
      <% if user_signed_in? %>
          <li><%= link_to "Product Categories", product_categories_path %></li>
      <% end %>
    </ul>
  </div>
  <div class="col-md-6 col-sm-12">
    <ul class="ta-PrimaryNavigationLinks" style="float: right;">
      <li>
        <% if user_signed_in? %>
            <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>
        <% else %>
            <%= link_to 'Log in', new_user_session_path %>
        <% end %>
      </li>
      <li><%= link_to "Vendor Application", vendor_signup_path %></li>
    </ul>
  </div>
</div>