config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  root 'static_pages#home'

  resources :vendors, only: [ :create ]
  resources :trades
  resources :boards

  get 'trade-signup',       to: "vendors#new"
  get 'vendor-signup',      to: "trades#new"
  get 'vendor-onboarding',  to: "boards#new"

  get 'trade_success',         to: 'static_pages#trade'
  get 'vendor_success',        to: 'static_pages#vendor'
  get 'board_success',         to: 'static_pages#board'
  get 'board_success_update',  to: 'static_pages#board_update'
  get 'trade_success_update',  to: 'static_pages#trade_update'
  get 'about',                 to: 'static_pages#about'
  get 'product_categories',    to: 'static_pages#product_categories'
  get 'upload_vendor_agreement_success',  to: 'static_pages#upload_vendor_agreement_success'

  get 'persons/profile', as: 'user_root'
  get 'upload-vendor-agreement-new',  to: 'persons#upload_vendor_agreement_new'
  post 'upload-vendor-agreement-new', to: 'persons#upload_vendor_agreement_create'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/board.rb
class Board < ActiveRecord::Base
  has_many :brands
  has_many :transportation_and_shipments
  has_many :vendor_carriers
  has_many :arbor_gentry_carriers
  has_many :product_types

  belongs_to :user, :dependent => :destroy

  mount_uploader :w_9_form, ImageUploader
  mount_uploader :certificate, ImageUploader


  accepts_nested_attributes_for :brands, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :transportation_and_shipments, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :vendor_carriers, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :arbor_gentry_carriers, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :product_types, reject_if: :all_blank, allow_destroy: true

  validates :primary_business_email, presence:  true

  def display_name
    # "#{first_name} #{last_name}"
  end
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  belongs_to :board
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :trade_categories, dependent: :destroy
  has_many :trades, through: :trade_categories
end

app/models/channel.rb
class Channel < ActiveRecord::Base
  has_many :trade_channels, dependent: :destroy
  has_many :trades, through: :trade_channels
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :vendor_companies, dependent: :destroy
  has_many :vendors, through: :vendor_companies
end

app/models/greeting.rb
class Greeting < ActiveRecord::Base
end

app/models/option.rb
class Option < ActiveRecord::Base
  has_many :trade_options, dependent: :destroy
  has_many :trades, through: :trade_options
end

app/models/product_type.rb
class ProductType < ActiveRecord::Base
  belongs_to :board
end

app/models/trade.rb
class Trade < ActiveRecord::Base

  belongs_to :user, :dependent => :destroy

  has_many :categories, :through =>  :trade_categories
  has_many :trade_categories, dependent: :destroy

  has_many :channels, :through =>  :trade_channels
  has_many :trade_channels, dependent: :destroy

  has_many :options, :through =>  :trade_options
  has_many :trade_options, dependent: :destroy

  has_many :information_trades, :dependent => :destroy

  validates :business_name, :greeting, :first_name, :last_name, :email, :phone_number, :address,
            :city, :state, :zipcode, :country, :web_site_url_my, presence:  true

  mount_uploader :image, ImageUploader

end

app/models/trade_category.rb
class TradeCategory < ActiveRecord::Base
  belongs_to :trade
  belongs_to :category
end

app/models/trade_channel.rb
class TradeChannel < ActiveRecord::Base
  belongs_to :trade
  belongs_to :channel
end

app/models/trade_option.rb
class TradeOption < ActiveRecord::Base
  belongs_to :trade
  belongs_to :option
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :board
  has_one :trade
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base

  has_many :companies, :through =>  :vendor_companies
  has_many :vendor_companies, dependent: :destroy

  validates :business_name, :greeting, :first_name, :last_name, :email, :phone_number, :address,
            :city, :state, :zipcode, :country, :web_site_url, presence:  true

  mount_uploader :image, ImageUploader

end

app/models/vendor_carrier.rb
class VendorCarrier < ActiveRecord::Base
  belongs_to :board
end

app/models/vendor_company.rb
class VendorCompany < ActiveRecord::Base
  belongs_to :vendor
  belongs_to :company
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def profile
   @user = User.find(current_user.id)
   @board_user = @user.board
   @trade_user = @user.trade
   @information_trades = @user.trade.information_trades
  end

  def upload_vendor_agreement_new
    @information_trade = InformationTrade.new
  end

  def upload_vendor_agreement_create
    @user = User.find(current_user.id)
    @trade = Trade.where(user_id: @user.id)
    if params[:information_trade].nil?
      @information_trade = InformationTrade.new
      flash[:warning] = "Please, upload a PDF!"
      render 'upload_vendor_agreement_new'
    else
      @information_trade = InformationTrade.new(vendor_agreement: params[:information_trade]['vendor_agreement'].tempfile, trade_id: @trade.first.id)
      @information_trade.save
      redirect_to upload_vendor_agreement_success_path
    end
  end

end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/persons/profile.html.erb
<div class="profile_container">
  <div class="top_block">
    <h1 class="home_subject">BECOME A VENDOR:</h1>

    <p class="home_banner">
      <span class="home_banner_span">TANDEM ARBOR</span> is an independent lifestyle e‐commerce site for highly curated
      home furnishings
      and designs catering to the higher end luxury consumer market. <span class="home_banner_span">TANDEM ARBOR</span>
      is constantly
      exploring the development of high‐end sub‐brands and exclusive arrangements with premier
      vendors, to further penetrate the market. We are able to implement amazing new technologies,
      that not only hold the hands of our customers, but truly influence the way furniture is curated,
      categorized, and most importantly purchased. <span class="home_banner_span">TANDEM ARBOR</span> is on trend and
      analytically
      proactive. Partner with us and discover what we can do for your business.
    </p>
  </div>
  <div class="step_blocks">
    <div class="step_block">
      <div class="left_block">
        <span class="step">STEP</span>

        <div class="number">
          <p>#<span>1.</span></p>
        </div>
      </div>
      <div class="content">
        <p class="content_text">
          Your Vendor Application has been approved! You may make updates to
          it <%= link_to 'here', edit_trade_path(@trade_user), class: 'content_link' if @trade_user %>.
        </p>
      </div>
      <div class="right_block">
        <%= link_to edit_trade_path(@trade_user) do %>
            <div class="block_center">
              <i class="fa fa-play" aria-hidden="true"></i>
            </div>
        <% end %>
      </div>
    </div>

    <div class="step_block ">
      <div class="left_block">
        <span class="step">STEP</span>

        <div class="number">
          <p>#<span>2.</span></p>
        </div>
      </div>
      <div class="content">
        <p class="content_text">
          Please review and sign
          the <%= link_to 'Vendor Agreement', '/Arbor Gentry Vendor Agreement.pdf', :download => "Arbor Gentry Vendor Agreement.pdf", class: 'content_link' %>
          .
          You may upload the completed Vendor
          Agreement <%= link_to 'here', upload_vendor_agreement_new_path, class: 'content_link' %>.
        </p>
      </div>
      <div class="right_block">
        <%= link_to '#' do %>
            <div class="block_center">
              <i class="fa fa-play" aria-hidden="true"></i>
            </div>
        <% end %>
      </div>
    </div>

    <div class="step_block ">
      <div class="left_block">
        <span class="step">STEP</span>

        <div class="number">
          <p>#<span>3.</span></p>
        </div>
      </div>
      <% if @information_trades.blank? %>
          <div class="content">
            <p class="content_text">
              NEXT IS <a href="#" class="content_link">VENDOR SETUP & ONBOARDING</a>. WE WILL REQUIRE SOME ADDITIONAL
              DETAILS TO REGISTER YOUR COMPANY TO ENSURE A SEAMLESS INTEGRATION.
            </p>
          </div>
          <div class="right_block">
            <%= link_to '#' do %>
                <div class="block_center">
                  <i class="fa fa-play" aria-hidden="true"></i>
                </div>
            <% end %>
          </div>
      <% else %>
          <div class="content">
            <p class="content_text">
              NEXT IS <%= link_to 'VENDOR SETUP & ONBOARDING', vendor_onboarding_path, class: 'content_link' %>. WE WILL REQUIRE SOME ADDITIONAL
              DETAILS TO REGISTER YOUR COMPANY TO ENSURE A SEAMLESS INTEGRATION.
            </p>
          </div>
          <div class="right_block">
            <%= link_to vendor_onboarding_path do %>
                <div class="block_center">
                  <i class="fa fa-play" aria-hidden="true"></i>
                </div>
            <% end %>
          </div>
      <% end %>
    </div>

    <div class="step_block disabled_block">
      <div class="left_block">
        <span class="step">STEP</span>

        <div class="number">
          <p>#<span>4.</span></p>
        </div>
      </div>
      <div class="content">
        <p class="content_text">
          FINALLY COMPLETE <a href="#" class="content_link">PRODUCT BUILDSHEET</a>. THIS WILL INCLUDE ALL OF THE
          DETAILS ABOUT EACH PRODUCT SO WE CAN MERCHANDISE IT ACCURATELY ON SITE.
        </p>
      </div>
      <div class="right_block">
        <%= link_to '#' do %>
            <div class="block_center">
              <i class="fa fa-play" aria-hidden="true"></i>
            </div>
        <% end %>
      </div>
    </div>
  </div>
  <p class="contact">If you have any questions, please contact us at
    <a href="mailto:hello@tandemarbor.com">hello@tandemarbor.com</a></p>
</div>

app/views/persons/upload_vendor_agreement_new.html.erb
<div class="upload_vendor_agreement_form">
  <%= form_for @information_trade, :url => url_for(:controller => "persons", :action => "upload_vendor_agreement_new") do |f| %>
      <div class="col-lg-12 form_container">
        <!-- col-lg-12 start here -->
        <div class="panel panel-default toggle panelMove panelClose panelRefresh log_in_panel">
          <!-- Start .panel -->
          <div class="panel-heading">
            <h4 class="panel-title">Upload Your Signed Vendor Agreement (.pdf)</h4>
          </div>

          <div class="form-group">
            <%= f.label :vendor_agreement, "File:", :class => "col-lg-2 col-md-3 control-label" %>
            <div class="col-lg-10 col-md-9">
              <%= f.file_field :vendor_agreement, :class => "form-control" %>
            </div>
          </div>

          <div class="form-group upload_save">
            <%= f.submit "Save", class: 'btn' %>
          </div>

        </div>
      </div>
  <% end %>
</div>